#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

function usage {
  cat <<END
usage: bootstrap [gzos|trusty]

Bootstrap a TEE development environment. Default: gzos
END
}

if [[ $# -gt 1 ]]; then
  usage
  exit 1
fi

tee=${1:-gzos}

declare manifest_name=""
declare manifest_file=""
declare manifest_url=""
declare manifest_branch=""

if [[ "${tee}" == "gzos" ]]; then
  manifest_name="garnet"
  manifest_file="manifest/garnet"
  manifest_url="ssh://review.gerrithub.io:29418/OpenTrustGroup/garnet"
  manifest_branch="gzos"
elif [[ "${tee}" == "trusty" ]]; then
  manifest_name="trusty"
  manifest_file="trusty"
  manifest_url="ssh://review.gerrithub.io:29418/OpenTrustGroup/manifest"
  manifest_branch="gzos"
else
  usage
  exit 1
fi

curl -s "https://fuchsia.googlesource.com/jiri/+/master/scripts/bootstrap_jiri?format=TEXT" | base64 --decode | bash -s "${tee}"
cd "${tee}"

.jiri_root/bin/jiri import -name="${manifest_name}" -remote-branch="${manifest_branch}" "${manifest_file}" "${manifest_url}"

.jiri_root/bin/jiri update

mkdir -p ~/bin
cp .jiri_root/bin/jiri ~/bin
rm -f ~/bin/fx
ln -sf `pwd`/scripts/fx ~/bin

echo "Done creating ${tee} development environment at \"$(pwd)\"."
echo "Recommended: export PATH=\"$HOME/bin:\$PATH\"
