#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### show backtrace from a logfile

## usage: fx backtrace [LOG_FILE]
##
## show backtrace from a logfile
##
## optional arguments:
##   LOG_FILE               Log file path (default: expect.log)
##

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh

"${FUCHSIA_DIR}/scripts/backtrace.py" "$@"
