#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build the kernel

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

if [[ -z ${ZIRCON_USER_PROJECT} ]]; then
  ZIRCON_USER_PROJECT="user"
fi

echo "Building zircon..."
"${FUCHSIA_DIR}/scripts/build-zircon.sh" -p "${ZIRCON_PROJECT}" -u "${ZIRCON_USER_PROJECT}" "$@"
