#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build Linux kernel

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

readonly LINUX_BUILDROOT="${FUCHSIA_OUT_DIR}/build-linux"
readonly LINUX_PATH="${FUCHSIA_DIR}/linux"
readonly LINUX_ARCH="arm64"
readonly SCRIPT_DIR="${FUCHSIA_DIR}/scripts"
readonly TOOLCHAIN_PREFIX="${LINARO_AARCH64_CROSS_COMPILE}"

JOBS=`getconf _NPROCESSORS_ONLN` || {
  Cannot get number of processors
  exit 1
}

set -eo pipefail; [[ "${TRACE}" ]] && set -x


declare VERBOSE="${VERBOSE:-0}"
declare CLEAN="${CLEAN:-false}"
declare PLATFORM="${PLATFORM:-qemu}"
declare LINUX_FLAGS="LOCALVERSION= O=${LINUX_BUILDROOT} ARCH=${LINUX_ARCH}"

usage() {
  printf '%s: [-c] [-v] [-p platform]\n' "$0"
  printf '  -c            clean & build\n'
  printf '  -v            show verbose compiling messages\n'
  printf '  -p [platform] select which platform to build, default: %s\n' "${PLATFORM}"
}

while getopts "chp:v" opt; do
  case "${opt}" in
    c) CLEAN="true" ;;
    h) usage ; exit 0 ;;
    p) PLATFORM="${OPTARG}" ;;
    v) VERBOSE="1" ;;
    *) usage 1>&2 ; exit 1 ;;
  esac
done

if [[ "${CLEAN}" = "true" ]]; then
  echo "Cleaning linux..."
  rm -rf -- "${LINUX_BUILDROOT}"
fi

if [[ "${USE_CCACHE}" = "1" ]]; then
  export CROSS_COMPILE="$(which ccache) ${TOOLCHAIN_PREFIX}"
else
  export CROSS_COMPILE="${TOOLCHAIN_PREFIX}"
fi

echo "Building linux..."

mkdir -p ${LINUX_BUILDROOT}

# Generate Linux .config file
cd ${LINUX_PATH} && \
ARCH=${LINUX_ARCH} \
scripts/kconfig/merge_config.sh -O ${LINUX_BUILDROOT} ${LINUX_PATH}/arch/arm64/configs/defconfig ${SCRIPT_DIR}/kconfigs/${PLATFORM}.conf

make -j ${JOBS} V=${VERBOSE} ${LINUX_FLAGS}
