#!/bin/bash
# Copyright 2018 Open Trust Group
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build extra linux tools

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

readonly TIPC_TEST_PATH="${FUCHSIA_DIR}/third_party/tipc-test"
readonly TIPC_TEST_BUILDROOT="${FUCHSIA_OUT_DIR}/build-tipc-test"

JOBS=`getconf _NPROCESSORS_ONLN` || {
  Cannot get number of processors
  exit 1
}

set -eo pipefail; [[ "${TRACE}" ]] && set -x

declare CLEAN="${CLEAN:-false}"

usage() {
  printf '%s: [-c]\n' "$0"
  printf '  -c            clean & build\n'
}

while getopts "chp:vl" opt; do
  case "${opt}" in
    c) CLEAN="true" ;;
    h) usage ; exit 0 ;;
    *) usage 1>&2 ; exit 1 ;;
  esac
done

if [[ "${CLEAN}" = "true" ]]; then
  echo "Cleaning extra linux tools' buildroot..."
  rm -rf -- "${TIPC_TEST_BUILDROOT}"
fi

echo "Building tipc-test..."
mkdir -p ${TIPC_TEST_BUILDROOT}
CROSS_COMPILE="${LINARO_AARCH64_CROSS_COMPILE}" BUILD_DIR="${TIPC_TEST_BUILDROOT}" make -C ${TIPC_TEST_PATH} all
