#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build third_party/qemu

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

echo "Building QEMU..."
"${FUCHSIA_DIR}/scripts/build-qemu.sh" "$@"

readonly QEMU_OUT_DIR="${FUCHSIA_OUT_DIR}/qemu-${HOST_TRIPLE}"
readonly QEMU_DIR="${FUCHSIA_DIR}/third_party/qemu"

echo ""
echo "Updating QEMU prebuilt binaries... "
cp -r ${QEMU_OUT_DIR}/* ${THIRD_PARTY_QEMU}/

last_commit="$(cd ${QEMU_DIR}; git log -1 --pretty=oneline)"
old_last_commit="$(cat ${THIRD_PARTY_QEMU}/last_commit)"

LIGHT_RED='\033[1;31m'
NC='\033[0m' # No Color
NOTICE="${LIGHT_RED}NOTICE:${NC}"

if [[ "${last_commit}" != "${old_last_commit}" ]]; then
  echo ${last_commit} > ${THIRD_PARTY_QEMU}/last_commit
  echo ""
  echo -e "${NOTICE} QEMU source code was changed. Remember to upload prebuilt files to gerrit for review."
  echo -e "${NOTICE} (file path: ${THIRD_PARTY_QEMU})"
  echo ""
fi
