#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build the kernel

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

BUILD_FLAGS="-p ${ZIRCON_PROJECT}"
if [[ ! -z ${ZIRCON_USER_PROJECT} ]]; then
  BUILD_FLAGS="${BUILD_FLAGS} -u ${ZIRCON_USER_PROJECT}"
fi

echo "Building zircon..."
"${FUCHSIA_DIR}/scripts/build-zircon.sh" ${BUILD_FLAGS} "$@"
