#!/bin/bash
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### build zircon, then build fuchsia
## build zircon, then build fuchsia

set -e

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read

if [[ -z "${TEE}" ]]; then
  fx-command-run build-zircon
  fx-command-run build
  exit 0
fi

if [[ "${TEE}" = "gzos" ]]; then
  fx-command-run build-zircon
  fx-command-run build
elif [[ "${TEE}" = "trusty" ]]; then
  fx-command-run build-trusty
fi

fx-command-run build-soc-term
fx-command-run build-linux
fx-command-run build-linux-rootfs
fx-command-run build-atf
