#!/bin/bash
# Copyright 2018 Open Trust Group
# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### set gzos build configuration

## usage: fx set-gzos TARGET [[--build-dir] OUTDIR]
##               [--boards B1,B2,...]
##               [--products P1,P2,...]
##               [--packages P1,P2,...]
##               [--netboot]
##               [--args ARG] [--help-args [ARG]] [--variant VARIANT]
##               [--ccache|--no-ccache]
##               [--release]
##               [--zircon-arg ARG]
##
## where TARGET is target platform or project
##
## OUTDIR is the directory where the build output goes.
## If it begins with `//` or `out/` then it's taken as relative to FUCHSIA_DIR.
## Otherwise it should be an absolute path or a path relative to the current
## working directory that winds up in `FUCHSIA_DIR/out`.
## It defaults to `out/TARGET`.
##
## This is a wrapper around running `gn gen --check OUTDIR --args ...`.
## If GN fails with an error, `fx set` does not change anything.
## If GN succeeds, this also points subsequent `fx` commands at OUTDIR,
## just as `fx use` does and ensures Goma is ready (if enabled).
##
## optional arguments:
##   --build-dir OUTDIR    Using this option is deprecated.  It's the same
##                         as just giving OUTDIR as a non-option argument.
##   --boards              Use the listed board target definition (seperated by
##                         comas) in the build, each board results in an import
##                         statement and MUST define the `fuchsia_packages`
##                         variable as well as deal with variable re-definition.
##   --products            Include the listed products (separated by commas) in
##                         the build. Defaults to the default product for the
##                         current layer (e.g., "garnet/packages/default" for
##                         the Garnet layer). If the --products argument is
##                         given multiple times, the products configurations
##                         are merged.
##   --packages            Additional packages to be built and made available.
##                         If the --packages argument is given multiple times,
##                         all the specified packages are included in the build.
##   --variant             Pass a `select_variant=[VARIANT*,...]` GN build argument
##                         collecting all the --variant arguments in order.
##   --fuzz-with           Pass a sanitizer name, e.g. "--fuzz-with asan" to
##                         enable ALL supporting fuzzers.  Use --variant for
##                         individual fuzzers, e.g. "--variant asan-fuzzer/foo".
##   --args                Additional argument to pass to gn. If the --args
##                         argument is given multiple times, all the specified
##                         arguments are passed to gn.
##                         N.B. Arguments must be expressed using GN's syntax.
##                         In particular this means that for strings they must
##                         be quoted with double-quotes, and the quoting must
##                         survive, for example, the shell. Thus when passing
##                         an argument that takes a string, pass it with
##                         something like --args=foo='"bar"'. E.g.,
##                         bash$ fx set x64 --args=foo='"bar"'
##                         More complicated arguments, e.g., lists, require
##                         their own special syntax. See GN documentation
##                         for the syntax of each kind of argument.
##   --help-args           Display GN arguments documentation.  If --help-args
##                         is followed by a GN build argument identifier, just
##                         that argument's documentation is displayed.
##                         If --help-args is used alone, all GN build arguments
##                         are displayed (lots of output).
##                         This option requires an existing build directory.
##   --ccache|--no-ccache  Whether to use ccache during the build. Ccache attempts
##                         to make builds faster by caching build artifacts.
##                         Defaults to detecting whether the CCACHE_DIR environment
##                         variable is set to a directory.
##   --release             an alias for "--args=is_debug=false"
##   --zircon-arg ARG      Additional arguments to pass to Zircon make. Can be given
##                         multiple times.

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/lib/vars.sh
fx-config-read-if-present

declare -A alias_projects=(
  ["gztee"]="gztee-arm64"
)

function is_third_party_project {
  if [[ $1 = *"-"* ]]; then true; else false; fi
}

function get_project_suffix {
  if [[ $1 = *"-"* ]]; then
    local str=(${1//-/ })
    echo ${str[-1]}
  else
    echo ""
  fi
}

declare project_list=""

tmp_list="$(ls ${FUCHSIA_DIR}/zircon/kernel/project/*.mk | xargs -I{} basename -s .mk {})"
for p in ${tmp_list}; do
  project_list="${project_list} ${p}"
done

function list_projects {
  echo  "available projects:"
  echo  "-------------------"
  for alias in "${!alias_projects[@]}"; do
    printf "%-25s (alias of %s)\n" "${alias}" "${alias_projects["${alias}"]}"
  done

  for p in ${project_list}; do
    printf "%-25s\n" "${p}"
  done
}

function search_projects {
  for alias in "${!alias_projects[@]}"; do
    if [[ "${alias}" = "${1}" ]]; then
      echo "${alias_projects["${alias}"]}"
      return 0
    fi
  done

  for p in ${project_list}; do
    if [[ "${p}" = "${1}" ]]; then
      echo "${p}"
      return 0
    fi
  done

  echo ""
}

function main {
  fx-standard-switches "$@"
  set -- "${FX_ARGV[@]}"

  if [[ $# -lt 1 ]]; then
    list_projects
    return 1
  fi

  local zircon_project="$(search_projects $1)"

  if [[ -z "${zircon_project}" ]]; then
    echo error: Unsupported project \"${1}\"
    list_projects
    return 1
  fi

  local arch=
  if $(is_third_party_project ${zircon_project}); then
    # third-party project should be suffixed with arch (e.g. gztee-arm64)
    local arch=$(get_project_suffix ${zircon_project})
  else
    local arch=${zircon_project}
  fi
  shift

  local gn_cmd='gen'
  local -a gn_switches=(--check)
  local gn_args="target_cpu=\"${arch}\""
  local boards=()
  local products=()
  local packages=()
  local zircon_args=()
  local extra_packages=()
  local build_dir=
  local variant=
  local ccache
  while [[ $# -ne 0 ]]; do
    case "$1" in
      --boards)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        # Multiple boards may be comma separated
        IFS=, boards+=("$2")
        shift
        ;;
      --products)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        # Multiple products may be comma separated
        IFS=, products+=("$2")
        shift
        ;;
      --packages)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        # Multiple packages may be comma separated
        IFS=, packages+=("$2")
        shift
        ;;
      --zircon-arg)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        zircon_args+=("$2")
        shift
        ;;
      --netboot)
        extra_packages+=('build/packages/netboot')
        ;;
      # TODO(mcgrathr): Remove this after a deprecation period.
      --build-dir)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        echo >&2 "NOTE: The --build-dir switch is deprecated; give $2 alone."
        build_dir="$2"
        shift
        ;;
      --release)
        gn_args+=" is_debug=false"
        ;;
      --variant)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        variant+="\"$2\","
        shift
        ;;
      --fuzz-with)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        variant+="{variant=\"$2-fuzzer\" target_type=[\"fuzzed_executable\"]},"
        shift
        ;;
      --args)
        if [[ $# -lt 2 ]]; then
          fx-command-help
          return 1
        fi
        gn_args+=" $2"
        shift
        ;;
      --help-args)
        gn_cmd=args
        if [[ $# -ge 2 ]] && [[ "$2" != '--*' ]]; then
          gn_switches+=("--list=$2")
          shift
        else
          gn_switches+=(--list)
        fi
        ;;
      --ccache)
        ccache=1
        ;;
      --no-ccache)
        ccache=0
        ;;
      --*)
        fx-command-help
        return 1
        ;;
      *)
        # A non-option argument is the build_dir, but there can be only one.
        if [[ -n "$build_dir" ]]; then
          fx-command-help
          return 1
        fi
        build_dir="$1"
        ;;
    esac
    shift
  done

  if $(is_third_party_project ${zircon_project}); then
    gn_args+=" zircon_project=\"${zircon_project}\""

    # Official zircon projects' kernel command line arguments are from
    # qemu '--append' parameter or other methods. Other third party
    # projects can put kernel command line arguments in bootdata by
    # providing 'kernel_cmdline_file' args to gen.py
    gn_args+=" kernel_cmdline_files=[\"//out/build-zircon/kernel_cmdline.txt\"]"

    # Official zircon projects' system partition is built by fuchisa's package manager.
    # For third party projects, we just use bootfs for system partition
    IFS=, extra_packages+=("build/packages/user_bootfs")

    # Zedboot image requires some binaries(e.g. netsvc) that may not available
    # in third party project. Thus we disable building zedboot image.
    gn_args+=" disable_zedboot=true"

    if [[ -z "${packages}" ]]; then
      IFS=, packages+=("garnet/packages/gzos")
    fi
  fi

  if [[ -z "${products}${packages}" ]]; then
    # This is the default logic GN would use, but if a user specified --netboot
    # we would short-circuit the logic, so repeat it here.
    local layers
    layers="$(${FUCHSIA_DIR}/build/gn/guess_layer.py)" || return 1
    readonly layers
    local layer
    for layer in $layers; do
      products+="${products:+,}$layer/products/default"
    done
  fi

  # Remove any trailing slash from build directory name.
  build_dir="${build_dir%/}"

  local config_build_dir
  case "$build_dir" in
    '')
      # Default is "//out/$target_cpu".  Store it as relative.
      config_build_dir="out/${arch}"
      build_dir="${FUCHSIA_DIR}/${config_build_dir}"
      ;;
    //*|out/*)
      # GN-style "source-relative" path or relative out/something.
      config_build_dir="${build_dir#//}"
      build_dir="${FUCHSIA_DIR}/${config_build_dir}"
      ;;
    *)
      # Absolute or relative path.  Canonicalize it to source-relative.
      local abs_build_dir
      abs_build_dir="$(cd "${build_dir%/*}"; pwd)/${build_dir##*/}" || {
        echo >&2 "ERROR: Missing parent directories for ${build_dir}"
        return 1
      }
      if [[ "$abs_build_dir" == "${FUCHSIA_DIR}"/out/* ]]; then
        config_build_dir="${abs_build_dir#${FUCHSIA_DIR}/}"
      else
        echo >&2 "WARNING: ${abs_build_dir} is not a subdirectory of ${FUCHSIA_DIR}/out"
        config_build_dir="$abs_build_dir"
      fi
      ;;
  esac

  for board in ${boards[@]}; do
    gn_args+=" import(\"//${board}\")"
  done

  gn_args+=" fuchsia_products=["
  for product in ${products[@]}; do
    gn_args+="\"${product}\","
  done
  gn_args+="]"

  if [[ -z "${boards}" ]]; then
  gn_args+=" fuchsia_packages=["
  else
    # Board configs MUST declare fuchsia_packages.
    gn_args+=" fuchsia_packages+=["
  fi
  for package in ${packages[@]} ${extra_packages[@]}; do
    gn_args+="\"${package}\","
  done
  gn_args+="]"

  if [[ -n "${variant}" ]]; then
    gn_args+=" select_variant=[${variant}]"
  fi

  mkdir -p "${build_dir}"
  echo "${zircon_args[@]}" > "${build_dir}.zircon-args"

  # Using a subshell with -x prints out the gn command precisely with shell
  # quoting so a cut&paste to the command line works.  Always show the real
  # meaning of what this script does so everyone learns how GN works.
  (
    set -x
    "${FUCHSIA_DIR}/buildtools/gn" ${gn_cmd} "${build_dir}" \
                                   "${gn_switches[@]}" --args="${gn_args}" "$@"
  # If GN failed, don't update .config.
  ) || return

  # Update config file
  cat >"${FUCHSIA_CONFIG}" <<END
# Generated by "fx set-gzos".
FUCHSIA_BUILD_DIR="${build_dir}"
FUCHSIA_ARCH="${arch}"
FUCHSIA_BUILD_ZIRCON_ARGS=(${zircon_args})
ZIRCON_PROJECT="${zircon_project}"
USE_CCACHE="${ccache}"
TEE="gzos"
END

}

main "$@"
